window.RAINBOW_TRANSLATIONS = [
 {
  "id": "BSB",
  "name": "Berean Standard Bible",
  "short": "BSB",
  "group": "Modern English",
  "blurb": "A modern, readable translation made directly from the Hebrew and Greek (2016–2023).",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "Berean Standard Bible",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/BSB",
  "red": false,
  "builtin": false
 },
 {
  "id": "WEB",
  "name": "World English Bible",
  "short": "WEB",
  "group": "Modern English",
  "blurb": "A modern update of the 1901 American Standard Version. Words of Jesus in red.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "World English Bible (Protestant edition)",
  "url": "https://ebible.org/engwebp/",
  "red": true,
  "builtin": false
 },
 {
  "id": "WEBU",
  "name": "World English Bible Updated",
  "short": "WEBU",
  "group": "Modern English",
  "blurb": "A later revision of the World English Bible.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "World English Bible Updated, eBible.org",
  "url": "https://ebible.org/engwebu/",
  "red": false,
  "builtin": false
 },
 {
  "id": "MSB",
  "name": "Majority Standard Bible",
  "short": "MSB",
  "group": "Modern English",
  "blurb": "The Berean Standard Bible, following the Majority Text in the New Testament.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "Majority Standard Bible, Berean Bible",
  "url": "https://ebible.org/engmsb/",
  "red": false,
  "builtin": false
 },
 {
  "id": "NHEB",
  "name": "New Heart English Bible",
  "short": "NHEB",
  "group": "Modern English",
  "blurb": "A modern public-domain revision of the World English Bible.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "New Heart English Bible",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/NHEB",
  "red": false,
  "builtin": false
 },
 {
  "id": "LSV",
  "name": "Literal Standard Version",
  "short": "LSV",
  "group": "Modern English",
  "blurb": "A modern, word-for-word literal translation (2020).",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "CC BY-SA (CC BY-SA 4.0)",
  "attribution": "Literal Standard Version © 2020 Covenant Press, CC BY-SA 4.0",
  "url": "https://ebible.org/englsv/",
  "red": false,
  "builtin": false
 },
 {
  "id": "FBV",
  "name": "Free Bible Version",
  "short": "FBV",
  "group": "Modern English",
  "blurb": "Contemporary, easy-to-read English (2018).",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "CC BY-SA (CC BY-SA 4.0)",
  "attribution": "Free Bible Version © 2018 Dr. Jonathan Gallagher, CC BY-SA 4.0",
  "url": "https://ebible.org/engfbv/",
  "red": false,
  "builtin": false
 },
 {
  "id": "T4T",
  "name": "Translation for Translators",
  "short": "T4T",
  "group": "Modern English",
  "blurb": "Very plain English that spells out meaning the original leaves implied.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "CC BY-SA (CC BY-SA 4.0)",
  "attribution": "Translation for Translators © 2008–2017 Ellis W. Deibler, Jr., CC BY-SA 4.0",
  "url": "https://ebible.org/eng-t4t/",
  "red": false,
  "builtin": false
 },
 {
  "id": "ULB",
  "name": "Unlocked Literal Bible",
  "short": "ULB",
  "group": "Modern English",
  "blurb": "A literal, open update of the American Standard Version (2017).",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "CC BY-SA (CC BY-SA 4.0)",
  "attribution": "Unlocked Literal Bible © 2017 Door43 World Missions Community, CC BY-SA 4.0",
  "url": "https://ebible.org/engULB/",
  "red": false,
  "builtin": false
 },
 {
  "id": "BBE",
  "name": "Bible in Basic English",
  "short": "BBE",
  "group": "Modern English",
  "blurb": "Written with a vocabulary of about 1,000 everyday words (1949/1964).",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "1949/1964 Bible in Basic English",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/BBE",
  "red": false,
  "builtin": false
 },
 {
  "id": "OEB",
  "name": "Open English Bible",
  "short": "OEB",
  "group": "Modern English",
  "blurb": "Modern English; a work in progress, so many books are not yet included.",
  "note": null,
  "coverage": "partial, 33% of verses",
  "license": "Public domain",
  "attribution": "Open English Bible (US Spelling)",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/OEB",
  "red": false,
  "builtin": false
 },
 {
  "id": "TCENT",
  "name": "Text-Critical English New Testament",
  "short": "TCENT",
  "group": "Modern English",
  "blurb": "A modern New Testament following the Byzantine Greek text (2022).",
  "note": null,
  "coverage": "New Testament only",
  "license": "CC BY (CC BY 4.0)",
  "attribution": "Text-Critical English New Testament © 2022 Robert Adam Boyd, CC BY 4.0",
  "url": "https://ebible.org/engtcent/",
  "red": false,
  "builtin": false
 },
 {
  "id": "KJV",
  "name": "King James Version",
  "short": "KJV",
  "group": "King James tradition",
  "blurb": "The Authorized Version of 1611 (1769 text). Words of Jesus in red.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "King James Version (eBible.org edition, with Strong's numbers and words of Jesus marked)",
  "url": "https://ebible.org/eng-kjv2006/",
  "red": true,
  "builtin": true
 },
 {
  "id": "KJVPCE",
  "name": "King James Version, Pure Cambridge Edition",
  "short": "KJVPCE",
  "group": "King James tradition",
  "blurb": "The Cambridge text of the KJV as printed around 1900.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "King James Version: Pure Cambridge Edition",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/KJVPCE",
  "red": false,
  "builtin": false
 },
 {
  "id": "UKJV",
  "name": "Updated King James Version",
  "short": "UKJV",
  "group": "King James tradition",
  "blurb": "The KJV with old words and grammar brought up to date.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "Updated King James Version",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/UKJV",
  "red": false,
  "builtin": false
 },
 {
  "id": "Webster",
  "name": "Webster Bible",
  "short": "Webster",
  "group": "King James tradition",
  "blurb": "Noah Webster's 1833 revision of the KJV.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "Webster Bible",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/Webster",
  "red": false,
  "builtin": false
 },
 {
  "id": "RNKJV",
  "name": "Restored Name King James Version",
  "short": "RNKJV",
  "group": "King James tradition",
  "blurb": "The KJV using Hebrew names for God.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "Restored Name King James Version",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/RNKJV",
  "red": false,
  "builtin": false
 },
 {
  "id": "ACV",
  "name": "A Conservative Version",
  "short": "ACV",
  "group": "King James tradition",
  "blurb": "A close, conservative update of the KJV's wording.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "A Conservative Version",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/ACV",
  "red": false,
  "builtin": false
 },
 {
  "id": "ASV",
  "name": "American Standard Version (1901)",
  "short": "ASV",
  "group": "Classic English",
  "blurb": "The American edition of the Revised Version, known for its literal style.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "American Standard Version (1901)",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/ASV",
  "red": false,
  "builtin": false
 },
 {
  "id": "RV",
  "name": "Revised Version (1881–1885)",
  "short": "RV",
  "group": "Classic English",
  "blurb": "The first official revision of the KJV, made in Britain.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "Revised Version, eBible.org",
  "url": "https://ebible.org/eng-rv/",
  "red": false,
  "builtin": false
 },
 {
  "id": "YLT",
  "name": "Young's Literal Translation",
  "short": "YLT",
  "group": "Classic English",
  "blurb": "Robert Young's very literal translation (1898).",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "Young's Literal Translation (1898)",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/YLT",
  "red": false,
  "builtin": false
 },
 {
  "id": "Darby",
  "name": "Darby Bible",
  "short": "Darby",
  "group": "Classic English",
  "blurb": "John Nelson Darby's literal translation (1890).",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "Darby Bible (1889)",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/Darby",
  "red": false,
  "builtin": false
 },
 {
  "id": "Rotherham",
  "name": "Rotherham's Emphasized Bible",
  "short": "Rotherham",
  "group": "Classic English",
  "blurb": "J. B. Rotherham's literal translation marking emphasis (1902).",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "The Emphasised Bible by J. B. Rotherham",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/Rotherham",
  "red": false,
  "builtin": false
 },
 {
  "id": "Geneva1599",
  "name": "Geneva Bible (1599)",
  "short": "Geneva",
  "group": "Historic English",
  "blurb": "The Bible of Shakespeare, the Puritans and the Mayflower.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "Geneva Bible (1599)",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/Geneva1599",
  "red": false,
  "builtin": false
 },
 {
  "id": "Tyndale",
  "name": "Tyndale Bible (1525–1530)",
  "short": "Tyndale",
  "group": "Historic English",
  "blurb": "William Tyndale's pioneering translation; he completed only part of the Old Testament.",
  "note": null,
  "coverage": "partial, 25% of verses",
  "license": "Public domain",
  "attribution": "William Tyndale Bible (1525/1530)",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/Tyndale",
  "red": false,
  "builtin": false
 },
 {
  "id": "Wycliffe",
  "name": "Wycliffe Bible (c. 1395)",
  "short": "Wycliffe",
  "group": "Historic English",
  "blurb": "The first complete English Bible, in Middle English, translated from the Latin.",
  "note": "Psalms and a few other chapters are numbered as in the Latin Vulgate, so some verses there sit one number away from the KJV.",
  "coverage": "Old and New Testaments",
  "license": "CC BY-SA (Creative Commons: BY-SA 4.0)",
  "attribution": "John Wycliffe Bible (c.1395)",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/enm/Wycliffe",
  "red": false,
  "builtin": false
 },
 {
  "id": "JPS",
  "name": "JPS Tanakh (1917)",
  "short": "JPS",
  "group": "Jewish and Messianic",
  "blurb": "The Jewish Publication Society's translation of the Hebrew Bible.",
  "note": "A few chapters follow Hebrew verse numbering, so some verses there sit one number away from the KJV.",
  "coverage": "Old Testament only",
  "license": "Public domain",
  "attribution": "Jewish Publication Society Old Testament",
  "url": "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/JPS",
  "red": false,
  "builtin": false
 },
 {
  "id": "OJB",
  "name": "Orthodox Jewish Bible",
  "short": "OJB",
  "group": "Jewish and Messianic",
  "blurb": "Hebrew Bible and New Testament in English with many Hebrew and Yiddish terms.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "CC BY (CC BY 4.0)",
  "attribution": "Orthodox Jewish Bible © 2002–2024 Artists for Israel International, CC BY 4.0",
  "url": "https://ebible.org/engojb/",
  "red": false,
  "builtin": false
 },
 {
  "id": "WMB",
  "name": "World Messianic Bible",
  "short": "WMB",
  "group": "Jewish and Messianic",
  "blurb": "The World English Bible using Hebrew names and terms.",
  "note": null,
  "coverage": "Old and New Testaments",
  "license": "Public domain",
  "attribution": "World Messianic Bible, eBible.org",
  "url": "https://ebible.org/engwmb/",
  "red": false,
  "builtin": false
 }
];
